# 风险评分权重配置
scoring_weights:
  alpha: 0.7  # 赔付率权重
  beta: 0.2   # 占比校准权重
  gamma: 0.05  # 出险率权重
  delta: 0.05  # 人均赔款归一化权重

# 数据目录配置
directories:
  original_data_files: "data_files"  # 订单数据文件目录
  logs: "Logs"  # 日志文件目录
  industry_json: "industry_classification"  # 行业分类JSON文件目录
  output: "output"  # 输出目录

# 文件命名配置
file_patterns:
  order_data_prefix: "order_data"  # 订单数据文件前缀
  industry_json_pattern:  # 行业分类JSON文件匹配模式
    LB: "国民行业分类_利宝"
    PA: "国民行业分类_平安"
  output_filename: "评分结果.xlsx"  # 输出文件名

# JSON导出配置
json_export:
  enabled: false  # 是否默认启用JSON导出
  subdirectory: "json_export"  # JSON导出子目录名
  skip_excel: true  # 是否默认跳过Excel文件生成

# 加费计算配置
surcharge_calculation:
  weight: 0.5 # 加费计算的权重系数，默认为1.0
  # 权重>1.0时：加大加费力度
  # 权重<1.0时：减小加费力度

# 保险公司配置
insurance_company:
  active: "LB"  # 当前激活的保险公司配置 [LB: 利宝, PA: 平安]
  
  # 利宝保险配置
  LB:
    amount_levels:  # 保额等级配置（单位：元）
      min: 100000
      max: 1000000
      step: 100000
    disability_levels:  # 伤残等级配置
      - "十级伤残:3%"
      - "十级伤残:5%"
      - "十级伤残:10%"
  
  # 平安保险配置
  PA:
    amount_levels:  # 保额等级配置（单位：元）
      min: 10000
      max: 1200000
      step: 10000
    disability_levels:  # 伤残等级配置
      - "工标:1%"
      - "工标:3%"
      - "工标:10%"
      - "行标:10%"

original_columns:
  # 如果您有需要跟踪的"原始特征"列，可放这里，和业务中其他逻辑配合
  #- 订单编号
  - 新单续保
  #- 起保日
  - 保期
  - 初始保费
  - 批改保费
  - 已赚保费
  - 报案数量
  - 累计赔付金额
  - 赔付比例
  #- 保额
  - 伤残
  #- 省份
  - 城市
  #- 行业1级
  - 行业2级
  #- 行业3级
  #- 行业4级
  - 新单承保人数
  - 最终承保人数
  - 30周岁以下（男）
  - 30-39周岁（男）
  - 40-49周岁（男）
  - 50-59周岁（男）
  - 60-64周岁（男）
  - 65周岁以上（男）
  - 30周岁以下（女）
  - 30-39周岁（女）
  - 40-49周岁（女）
  - 50-59周岁（女）
  - 60-64周岁（女）
  - 65周岁以上（女）
  - 一类参保
  - 二类参保
  - 三类参保
  - 四类参保
  - 五类参保
  - 一类未参保
  - 二类未参保
  - 三类未参保
  - 四类未参保
  - 五类未参保
  - 涉高一类参保
  - 涉高二类参保
  - 涉高三类参保
  - 涉高四类参保
  - 涉高五类参保
  - 涉高一类未参保
  - 涉高二类未参保
  - 涉高三类未参保
  - 涉高四类未参保
  - 涉高五类未参保
  - 涉高率
  - 参保率
  - 批改率
  - 经过天数
